linux-2.6-BRANCH		:= f12
linux-2.6-GITPATH		:= git://git.onelab.eu/linux-2.6.git@linux-2.6.32-f12
kernel-STOCK-DEVEL-RPMS		+= elfutils-libelf-devel 
kernel-STOCK-DEVEL-RPMS		+= e2fsprogs 
util-vserver-BRANCH		:= f12
util-vserver-GITPATH		:= git://git.onelab.eu/util-vserver.git@f12
util-vserver-STOCK-DEVEL-RPMS		+= nss nss-devel
#util-vserver-STOCK-DEVEL-RPMS		+= dietlibc
yum-BRANCH			:= f12
yum-SVNPATH			:= http://svn.planet-lab.org/svn/yum/branches/f12@16162
